language: node_js
node_js:
  - "6"
  - "6.1"
  - "5.11"
  - "4.4"
before_script:
  # install dev dependnecies
  - npm install
script:
  # check linting and type annotation pass
  - make lint-prod

  # run test suites
  - make test

  # build the web app
  # deferred until there is a reason to build the app (webpack does not exit
  # with error on partial failure).
  # - make web app
  # - MD_LIVE_BUILD=prod make web app

