language: node_js
node_js:
  - "6"
before_script:
  # install dev dependnecies
  - npm install
script:
  # check linting and type annotation pass
  - make lint

  # build the web app
  - make web app
  - MD_LIVE_BUILD=prod make web app

